######################################
#                                    #
#   Configuration file for Skyrama   #
#            v1.0.1-ALPHA            #
#                                    #
######################################

mysql:
  host: localhost
  port: 3306
  name: Skyrama
  user: Skyrama
  password: Skyrama!!

# General plugin settings
general:

  # the name of Island schematic
  schematic: island.schematic

  # Language of the plugin (location: './locales/en_US.yml')
  # Avaible: en_US , de_DE
  locale: en_US

  # Name of the world where floating islands spawn
  world: skyrama

  # PREFIX for all messages §f{PREFIX}
  prefix: §7[§bSkyrama§7]

# Island chat settings
chat:

  # Enable the Join and Quit Messages
  join-quit-messages: true

  # Enable or disable the chat function (true, false)
  global-chat: false

  # message for Globalchat
  global-chat-message: §c{0} §7- §f{msg}

  # Enable or disable the Island chat function (true, false)
  island-chat: false

  # message for Islandchat
  island-chat-message: §cIsland §f| §c{0} §7- §f{msg}

# Vault related settings
vault:

  # Enable or Disable the player need Money to create her Island
  enable: false

  # Price to create Island
  island-costs: 500.00

  # Enable or Disable the player need Money to Invite players to his Island
  island-invite-enable: false


  # Price to Invite a Players
  island-invite-price: 100.00

# Island related settings
island:

  # Name of the default island schematic in folder ./schematics/******.schem
  schematic: island

  # Distance between each islands in blocks
  # DON'T CHANGE THIS VALUE IN MID GAME /!\
  distance: 256

  # Different island extension size in blocks (island width)
  # DON'T CHANGE THIS VALUE IN MID GAME /!\
  extension_level:
    0: 65
    1: 129
    2: 257
    3: 513

  # Enable PVP between members of the island
  pvpIslandPlayer: false

  # Enable PVP with island visitors
  pvpIslandVisitor: false

  # Enable spawn on island when login
  spawnIslandLogin: true

  # Enable respawn on island when player die
  respawnIsland: true

  # Enable Inventory save on die
  respawnInventorySave: true
