name: Skyrama
version: ${project.version}
main: de.skyrama.Skyrama
api-version: 1.19
authors: [ Kozen, DevSnx ]
description: Skyblock plugin for Minecraft 1.19
commands:
  island:
    description: Island command
    aliases: is