name: Skyrama
version: 1.0.0
main: de.skyrama.Skyrama
api-version: 1.19
authors: [ Kozen, DevSnx ]
description: Skyblock plugin for Minecraft 1.19
depend:
  - WorldEdit
  - Vault
commands:
  island:
    description: Island command
    aliases: is